# Reshape, Flatten, Ravel 

In [5]:
import numpy as np

arr = np.arange(1, 13)

arr_3x4 = arr.reshape(3, 4)
arr_2x6 = arr.reshape(2, 6)

print("3 x 4 Array:\n", arr_3x4)
print("\n2 x 6 Array:\n", arr_2x6)

3 x 4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

2 x 6 Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [7]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Flatten --> creates a copy
flat_arr = arr2.flatten()

# Ravel --> creates a view
ravel_arr = arr2.ravel()

flat_arr[0] = 100
ravel_arr[1] = 200

print("Original Array after changes:\n", arr2)
print("\nFlattened Array:\n", flat_arr)
print("\nRaveled Array:\n", ravel_arr)


Original Array after changes:
 [[  1 200   3]
 [  4   5   6]]

Flattened Array:
 [100   2   3   4   5   6]

Raveled Array:
 [  1 200   3   4   5   6]


In [9]:
arr3 = np.arange(1, 10).reshape(3, 3)
print("Original 3x3 Array:\n", arr3)

flat1 = arr3.flatten()
ravel1 = arr3.ravel()

print("\nFlattened 1D Array:\n", flat1)
print("Raveled 1D Array:\n", ravel1)

# Change ravel to show effect on original
ravel1[0] = 999
print("\nModified Ravel --> Original Array Changes:\n", arr3)


Original 3x3 Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened 1D Array:
 [1 2 3 4 5 6 7 8 9]
Raveled 1D Array:
 [1 2 3 4 5 6 7 8 9]

Modified Ravel --> Original Array Changes:
 [[999   2   3]
 [  4   5   6]
 [  7   8   9]]
