# Indexing and Slicing

In [1]:
import numpy as np

arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print("Original Array:\n", arr)


Original Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [2]:
# 1. Extract the second row
print("Second Row:\n", arr[1])

# 2. Extract first two rows & second two columns
print("\nFirst 2 Rows and Last 2 Columns:\n", arr[:2, 2:])

# 3. Extract last column using slicing
print("\nLast Column:\n", arr[:, -1])

# 4. Replace middle row with [1, 2, 3, 4]
arr[1] = [1, 2, 3, 4]
print("\nAfter Replacing Middle Row:\n", arr)


Second Row:
 [50 60 70 80]

First 2 Rows and Last 2 Columns:
 [[30 40]
 [70 80]]

Last Column:
 [ 40  80 120]

After Replacing Middle Row:
 [[ 10  20  30  40]
 [  1   2   3   4]
 [ 90 100 110 120]]
