# Array Creation and Data Types

In [1]:
import numpy as np

# 1D array of integers from 1 to 10
arr1 = np.arange(1, 11)

# 2D array of size 3×3 with numbers from 1–9
arr2 = np.arange(1, 10).reshape(3, 3)

print("1D Array:\n", arr1)
print("\n2D Array:\n", arr2)


1D Array:
 [ 1  2  3  4  5  6  7  8  9 10]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
# For 1D Array
print("---- 1D Array Info ----")
print("Dimensions:", arr1.ndim)
print("Shape:", arr1.shape)
print("Size:", arr1.size)
print("Data Type:", arr1.dtype)
print("Item Size:", arr1.itemsize, "bytes")

# For 2D Array
print("\n---- 2D Array Info ----")
print("Dimensions:", arr2.ndim)
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data Type:", arr2.dtype)
print("Item Size:", arr2.itemsize, "bytes")


---- 1D Array Info ----
Dimensions: 1
Shape: (10,)
Size: 10
Data Type: int64
Item Size: 8 bytes

---- 2D Array Info ----
Dimensions: 2
Shape: (3, 3)
Size: 9
Data Type: int64
Item Size: 8 bytes


In [4]:
float_arr = np.array(
    [[1.1, 2.2, 3.3],                  
    [4.4, 5.5, 6.6],
    [7.7, 8.8, 9.9]
    ])

int_arr = float_arr.astype(int)

print("Float Array:\n", float_arr)
print("\nConverted Integer Array:\n", int_arr)


Float Array:
 [[1.1 2.2 3.3]
 [4.4 5.5 6.6]
 [7.7 8.8 9.9]]

Converted Integer Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
