# Broadcasting

In [2]:
import numpy as np

A = np.arange(1, 10).reshape(3, 3)
print("Matrix A:\n", A)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Predicted Shapes:
- A + 10 --> (3, 3) 
- A + [1, 2, 3] --> (3, 3) 
- A + [[1], [2], [3]] --> (3, 3)


In [3]:
# Scalar broadcasting
print("\nA + 10:\n", A + 10)


A + 10:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [4]:
# Row vector broadcasting
row_vec = np.array([1, 2, 3])
print("\nA + [1, 2, 3]:\n", A + row_vec)


A + [1, 2, 3]:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [5]:
# Column vector broadcasting
col_vec = np.array([[1], [2], [3]])
print("\nA + column vector [[1], [2], [3]]:\n", A + col_vec)


A + column vector [[1], [2], [3]]:
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
