# Array Creation Functions

In [1]:
import numpy as np

# a) Zero matrix (4×4)
zeros_arr = np.zeros((4, 4))
print("Zero Matrix (4×4):\n", zeros_arr, "\n")

# b) One matrix (3×2)
ones_arr = np.ones((3, 2))
print("One Matrix (3×2):\n", ones_arr, "\n")

# c) Identity matrix (5×5)
identity_arr = np.eye(5)
print("Identity Matrix (5×5):\n", identity_arr, "\n")

# d) Constant values array filled with 7
const_arr = np.full((3, 3), 7)
print("Constant Array (3×3) with 7s:\n", const_arr, "\n")

# e) Random integer array (3×4), values between 10 and 99
rand_arr = np.random.randint(10, 99, (3, 4))
print("Random Integer Array (3×4):\n", rand_arr)


Zero Matrix (4×4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

One Matrix (3×2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]] 

Identity Matrix (5×5):
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

Constant Array (3×3) with 7s:
 [[7 7 7]
 [7 7 7]
 [7 7 7]] 

Random Integer Array (3×4):
 [[22 43 77 47]
 [81 65 41 21]
 [55 37 45 83]]


In [2]:
# Generate array from 5 to 50 with step 5
arr = np.arange(5, 50, 5)

# Reshape into 3×3
reshaped_arr = arr.reshape(3, 3)
print("Array reshaped to 3×3:\n", reshaped_arr)

Array reshaped to 3×3:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
